### ISSUE TITLE
Complex numbers support

### ISSUE THREAD

**Issue by pierreguilmin** [f0uriest/quadax#19]
Thanks a lot for your excellent library! 👏

When integrating a complex-valued function, for example just just changing the README example to `fun = lambda t: t * jnp.log(1 + t) * 1j`, I get a `TypeError`:
```python
TypeError: true_fun and false_fun output must have identical types, got
('ShapedArray(complex64[])', 'ShapedArray(float32[], weak_type=True)', 'DIFFERENT ShapedArray(complex64[]) vs. ShapedArray(float32[])', 'DIFFERENT ShapedArray(complex64[]) vs. ShapedArray(float32[])').
```

This happens even when the norm is real-valued (which is [the default](https://github.com/f0uriest/quadax/blob/main/quadax/adaptive.py#L411C51-L411C89) anyway I think).

**Comment by f0uriest** [comment]
Thanks, this was due to some type mismatches when shortcutting a zero length interval. Should be fixed by #20
